#!/usr/bin/env python3
"""
Check sleep.yaml for accommodations flagged with warnings:
  - temporarily closed
  - closed on [day]
  - negative reviews
Outputs warnings.md.

No dependencies beyond Python stdlib.
Usage: python3 check-warnings.py [path-to-yaml] > sleep/warnings.md
"""

import sys
import re
from datetime import datetime, timezone

path = sys.argv[1] if len(sys.argv) > 1 else "sleep/sleep.yaml"

with open(path) as f:
    content = f.read()

# Split into day blocks
day_blocks = re.split(r'\n(?=\w)', content)

KEYWORDS = {
    "temporarily closed": "🔴 Temporarily closed",
    "closed on":          "🟡 Closed on certain days",
    "negative review":    "⚠️  Negative reviews reported",
    "pick-up point":      "ℹ️  Not a walk-in — pick-up point only",
}

warnings = []

for block in day_blocks:
    key_match = re.match(r'^(\S+):', block)
    if not key_match:
        continue
    day_key = key_match.group(1)
    label   = day_key.replace('_', ' ').title()

    # Split into individual item segments
    segments = re.split(r'\n    - name: ', block)
    for seg in segments[1:]:
        name_match = re.match(r'(.+)', seg)
        if not name_match:
            continue
        name = name_match.group(1).strip()

        note_match = re.search(r'note: (.+)', seg)
        if not note_match:
            continue
        note = note_match.group(1).strip()

        # Check for warning keywords
        for kw, flag in KEYWORDS.items():
            if kw.lower() in note.lower():
                # Also grab votes if any, to show if someone voted for this
                votes_match = re.search(r'votes:\n((?:[ \t]+\w+:.*\n)*)', seg)
                voted_for = []
                if votes_match:
                    for line in votes_match.group(1).splitlines():
                        vm = re.match(r'[ \t]+(\w+):[ \t]*(.*)', line)
                        if vm and vm.group(2).strip():
                            if name.lower() in vm.group(2).strip().lower():
                                voted_for.append(vm.group(1))
                warnings.append({
                    "day":       day_key,
                    "label":     label,
                    "name":      name,
                    "note":      note,
                    "flag":      flag,
                    "voted_for": voted_for,
                })
                break

# ── Output markdown ──────────────────────────────────────────────
now_str = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")

print("# Camino del Norte – Accommodation Warnings")
print(f"\n_Last checked: {now_str}_\n")

if not warnings:
    print("✅ No warnings found — all voted accommodations look good.")
    sys.exit(0)

# Group by type
closed      = [w for w in warnings if "closed" in w["flag"].lower()]
flagged     = [w for w in warnings if "closed" not in w["flag"].lower()]

print(f"**{len(closed)}** temporarily closed &nbsp;|&nbsp; **{len(flagged)}** other warnings\n")
print("> These are accommodations listed in `sleep.yaml` that have known issues.")
print("> Verify status before booking or choose an alternative for that stage.\n")
print("---\n")

if closed:
    print("## 🔴 Temporarily Closed / Restricted\n")
    for w in closed:
        voted_note = ""
        if w["voted_for"]:
            names = ", ".join(w["voted_for"])
            voted_note = f"\n> ⚠️  **{names} voted for this** — please update your vote in `sleep.yaml`"
        print(f"### {w['name']}")
        print(f"**Stage:** {w['label'].replace('Day ', 'Day ').replace(' To ', ' → ')}")
        print(f"**Status:** {w['flag']}")
        print(f"**Note:** _{w['note']}_")
        if voted_note:
            print(voted_note)
        print()

if flagged:
    print("## ⚠️  Other Warnings\n")
    for w in flagged:
        voted_note = ""
        if w["voted_for"]:
            names = ", ".join(w["voted_for"])
            voted_note = f"\n> ⚠️  **{names} voted for this** — please review"
        print(f"### {w['name']}")
        print(f"**Stage:** {w['label']}")
        print(f"**Status:** {w['flag']}")
        print(f"**Note:** _{w['note']}_")
        if voted_note:
            print(voted_note)
        print()

print("---")
print("_This file is auto-generated by `check-warnings.py` on every push to `sleep/sleep.yaml`._")
print("_To suppress a warning, remove or update the `note:` field for that accommodation._")